---
title: "ex_11_ggplot"
output: pdf_document
date: "2024-07-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#12.1
library(vctrs)
library(tidyverse)
head(mpg)
mpg %>% ggplot() # Blank screen 
```

```{r}
#12.2
ggplot(data=mpg, aes(x=cyl, y=hwy)) +
      geom_point()
```

```{r}
#12.3
# two categorical axes not good for scatter 
ggplot(data=mpg, aes(x=drv, y=class)) +
  geom_point() 
```

```{r}
#12.4
x <- seq(-6*pi, 6*pi, length.out = 100)
y = sin(x)/x
data = data.frame(x = x, y = y)
data
ggplot(data = data, aes(x=x, y=y)) +
         geom_point()
```

```{r}
#12.5
ggplot(data=cars, mapping = aes(x=dist, y=speed)) +
  geom_point()
```

```{r}
#12.6
gg =  (ggplot(data=cars, mapping = aes(x=dist, y=speed)) +
      geom_point(aes(color= dist>80)))
gg
```


```{r}
#12.7
ggplot(data=cars, mapping = aes(x=dist, y=speed)) +
  geom_point(mapping = aes(dist<80)) +
  scale_colour_manual(
  name='Legend', 
  values=c('red', 
            'blue' ))
```

```{r}
#12.8
gg + geom_smooth(method = 'lm')

```

```{r}
#12.9
 hist_dist = ggplot(data=cars, mapping = aes(x=dist)) +
      geom_histogram(bins=10)

 hist_speed = ggplot(data=cars, mapping = aes(x=speed)) +
      geom_histogram(bins=10)
 hist_dist
 hist_speed

```

```{r}
#12.10
 mpg %>% ggplot() + 
  geom_point(aes(
    x = hwy,
    y = cty)) + 
  facet_grid(drv~cyl)
```

```{r}
#12.11
ggplot(data=iris, aes(x=Sepal.Length, y=Sepal.Width, color=Species, shape=Species)) + 
  geom_point() +
  geom_density2d() + 
  theme_dark()
```

```{r}
#12.12
```

```{r}
#12.13
```

```{r}
#12.14
```